services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-container
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" > /dev/null || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s

  travelbuddyapi:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: travel-buddy-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - GEOAPIFY__KEY=${GEOAPIFY__KEY}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - COGNITO__AUTHORITY=${COGNITO__AUTHORITY}
      - COGNITO__AUDIENCE=${COGNITO__AUDIENCE}
      - ConnectionStrings__TravelBuddyDb=Server=sqlserver;Database=TravelBuddyDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "80:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserverdata: